name: deploy master

on:
  push:
    branches:
      - master

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test
        env:
          NODE_ENV: test
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_URI: ${{ secrets.REDIS_URI }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          FILEBASE_ENDPOINT: ${{ secrets.FILEBASE_ENDPOINT }}
          FILEBASE_REGION: ${{ secrets.FILEBASE_REGION }}

      - name: deploy on machine via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/explorer-api
            git reset --hard HEAD
            git pull origin master
            npm i
            pm2 restart index.js
